// frontend/vue/src/App.vue
<script setup>
import { ref, onMounted } from 'vue'

const tasks = ref([])
const newTask = ref('')

const createTask = async () => {
  if (!newTask.value.trim()) return

  const res = await fetch('http://localhost:8000/tasks', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ text: newTask.value })
  })

  const created = await res.json()
  tasks.value = [...tasks.value, created].sort((a, b) => a.id - b.id)

  newTask.value = ''
}

const deleteTask = async (id) => {
  await fetch(`http://localhost:8000/tasks/${id}`, {
    method: 'DELETE'
  })

  tasks.value = tasks.value.filter(t => t.id !== id)
}

const loadTasks = async () => {
  const res = await fetch('http://localhost:8000/tasks')
  const data = await res.json()
  tasks.value = data.sort((a, b) => a.id - b.id)
}

const toggleTask = async (id) => {
  await fetch(`http://localhost:8000/tasks/${id}/toggle`, {
    method: 'PATCH'
  })

  tasks.value = tasks.value.map(t =>
    t.id === id ? { ...t, completed: !t.completed } : t
  )
}

onMounted(() => {
  loadTasks()
})
</script>

<template>
  <div style="padding: 2rem; max-width: 600px; margin: 0 auto;">
    <h1>Tasks</h1>

    <ul>
      <li v-for="task in tasks" :key="task.id" class="row">
        <span
          class="text"
          :style="{ textDecoration: task.completed ? 'line-through' : 'none' }"
        >
          {{ task.text }}
        </span>

        <div class="actions">
          <button @click="toggleTask(task.id)">toggle</button>
          <button @click="deleteTask(task.id)">delete</button>
        </div>
      </li>
    </ul>
  </div>
</template>

// frontend/react/src/App.jsx
import { useState, useEffect, useRef } from 'react'
import './App.css'

function App() {
  const [tasks, setTasks] = useState([])
  const [editingId, setEditingId] = useState(null)
  const [editValue, setEditValue] = useState("")
  const editRef = useRef(null)

  const deleteTask = async (id) => {
    await fetch(`http://localhost:8000/tasks/${id}`, {
      method: "DELETE",
    })

    fetchTasks()
  }

  const fetchTasks = async () => {
    const res = await fetch("http://localhost:8000/tasks")
    const data = await res.json()
    data.sort((a, b) => a.id - b.id)
    setTasks(data)
  }

  const toggleTask = async (id) => {
    await fetch(`http://localhost:8000/tasks/${id}/toggle`, {
      method: "PATCH",
    })

    await fetchTasks()
  }

  useEffect(() => {
    setTimeout(() => {
      fetchTasks()
    }, 0)
  }, [])

  useEffect(() => {
    const handleClick = (e) => {
      if (editingId !== null && editRef.current && !editRef.current.contains(e.target)) {
        setEditingId(null)
        setEditValue("")
      }
    }

    document.addEventListener("mousedown", handleClick)
    return () => document.removeEventListener("mousedown", handleClick)
  }, [editingId])

  return (
    <div style={{ padding: '2rem', maxWidth: '600px', margin: '0 auto' }}>
      <h1>Tasks</h1>

      <form
        onSubmit={async (e) => {
          e.preventDefault()
          const title = e.target.title.value

          await fetch('http://localhost:8000/tasks', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ title }),
          })

          e.target.reset()
          fetchTasks()
        }}
      >
        <input name="title" placeholder="New task" required />
        <button type="submit">Add</button>
      </form>
      <ul>
        {tasks.map((task) => (
          <li key={task.id} className="task">
            {editingId === task.id ? (
              <div ref={editRef}>
                <input
                  value={editValue}
                  onChange={(e) => setEditValue(e.target.value)}
                />
                <button
                  onClick={async () => {
                    await fetch(`http://localhost:8000/tasks/${task.id}`, {
                      method: 'PUT',
                      headers: { 'Content-Type': 'application/json' },
                      body: JSON.stringify({ title: editValue }),
                    })

                    setEditingId(null)
                    setEditValue("")
                    fetchTasks()
                  }}
                >
                  save
                </button>
              </div>
            ) : (
              <>
                <span style={{ textDecoration: task.completed ? 'line-through' : 'none' }}>
                  {task.title}
                </span>

                <div className="actions">
                  <button
                    onClick={() => {
                      setEditingId(task.id)
                      setEditValue(task.title)
                    }}
                  >
                    edit
                  </button>

                  <button onClick={() => toggleTask(task.id)}>
                    toggle
                  </button>

                  <button onClick={() => deleteTask(task.id)}>
                    delete
                  </button>
                </div>
              </>
            )}
          </li>
        ))}
      </ul>
    </div>
  )
}

export default App
